# This is a basic workflow to help you get started with Actions

name: Shellcheck Problem Matchers

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branch:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    uses: lumaxis/shellcheck-problem-matchers@v1
    steps:
      
      run: shellcheck -f gcc *.sh
